System:
  Permissions:
    Use:
      # Should a user have the 'iConomy.holdings' to use /money
      # By default this is false, so that people stop complaining that
      # iConomy doesn't work. Yes, people actually report that.
      # If you are one of those people, leave this false.
      Holdings: false

  Default:
    Currency:
      Name: Dollar
      MultiWorld: false

    Account:
      # Default account balance when created
      Holdings: 30.0

  PayDay:
    Enabled: [default]
  # Controls how money is formatted through methods
  Formatting:
    # Minor allows you to use the Minor amounts for amounts <1
    # Example (true) 0.23 Coins and 1.23 Dollars (false) 0.23 Dollars and 1.23 Dollars
    Minor: false

    # Seperate allows your money to be shown in an alternative way,
    # instead of 1.32 it will show as 1 Dollar 23 Coins
    # !!! NOTICE: This only works if Minor is set to true !!!
    Seperate: false                               # Example (true) 1 Dollar, 23 Coins (false) 1.23 Dollars (Only if Minor is true)

    # Single shows your money in another alternative way.
    # Instead of 1.23 Dollars you will see: 1 Dollar.
    # If your money is 0.23 you will see 0 Dollars if Minor is false, 23 Coins if Minor is true.
    # !!! Notice: This overrides seperate !!!
    Single: false

  # Logs all monetary transactions passed through iConomy
  Logging:
    Enabled: false

  # Controls amount of money gained at a set interval.
  Interest:
    Enabled: false

    # Only give interest to players who are currently online?
    Online: true

    Announce:
      # Send a message when the player gains interest?
      Enabled: false

    Interval:
      #  Interval is done in seconds, here is a easy reference table for commonly set intervals:
      #   1 minute = 60 seconds
      #   1 hour = 1 minute * 60 = 3600 seconds
      #   1 day = 1 hour * 24 = 86400 seconds
      #   1 week = 1 day * 7 = 604800 seconds
      Seconds: 60

    Amount:
      # The balance to be met where we stop giving interest.
      # 0.0 for no limit
      Cutoff: 0.0

      # Percentage of holdings to give / take (Negative to take) (Overrides Min/Max)
      Percent: 0.0

      # This is range based, to set a "flat" or "constant" rate, set each (Maximum and Minimum) to the same number.
      # If the two numbers are different, it will be a random amount in-between the two.
      Maximum: 1
      Minimum: 2

  Database:
    # Databases Supported:
    ##
    # mysql
    #  - These will attempt to connect to MySQL
    ##
    # sqlite
    #  - These will attempt to create & connect to SQLite
    Type: 'sqlite'

    # The table used for the money
    MoneyTable: 'Craftconomy'

    # The table used for the bank
    BankTable: 'Bank'
    
    CurrencyTable: 'Currency'
    
    BalanceTable: 'Balance'

    #Modify if using MySQL
    Address: 'localhost'
    Port: 3306
    Username: 'root'
    Password: ''
    Db: 'Craftconomy'