System:
  Default:
    Currency:
      Name: Dollar
      MultiWorld: false

    Account:
      # Default account balance when created
      Holdings: 30.0

  Bank:
    Price: 50
    Currency: Dollar
    
  PayDay:
    Enabled: [default]

  # Logs all monetary transactions passed through iConomy
  Logging:
    Enabled: false

  Convert:
    Enabled: false
    Type: iconomy
    TableName: iConomy
    DatabaseType: mysql
    Address: localhost
    Port: 3306
    Username: root
    Password: test
    Database: iconomy
    
  Database:
    # Databases Supported:
    ##
    # mysql
    #  - These will attempt to connect to MySQL
    ##
    # sqlite
    #  - These will attempt to create & connect to SQLite
    Type: 'sqlite'

    # The table used for the accounts
    AccountTable: 'Account'
    BalanceTable: 'Balance'
    
    # The table used for the bank
    BankTable: 'Bank'
    BankBalanceTable: 'BankBalance'
    BankMemberTable: 'BankMember'
    
    CurrencyTable: 'Currency'
    CurrencyExchangeTable: 'CurrencyExchange'    
    
    #Modify if using MySQL
    Address: 'localhost'
    Port: 3306
    Username: 'root'
    Password: ''
    Db: 'Craftconomy'