name: Craftconomy
main: me.greatman.Craftconomy.Craftconomy
version: 1.0.0-b${BUILD_NUMBER}
load: startup
commands:
    money:
      aliases: [craftconomy]
      description: Check / Distribute currency.
    bank:
      description: Check /Distribute money on a Bank.
permissions:
    Craftconomy.*:
        default: op
        description: Gives access to all commands
        children:
            Craftconomy.help: true
            Craftconomy.holdings: true
            Craftconomy.holdings.others: true
            Craftconomy.payment: true
            Craftconomy.accounts.create: true
            Craftconomy.accounts.remove: true
            Craftconomy.accounts.give: true
            Craftconomy.accounts.take: true
            Craftconomy.accounts.set: true
            Craftconomy.accounts.purge: true
            Craftconomy.accounts.empty: true
            Craftconomy.banks.give: true
            Craftconomy.banks.take: true
            Craftconomy.banks.set: true
            Craftconomy.banks.holdings: true
            Craftconomy.banks.holdings.others: true
            Craftconomy.bank.deposit: true
            Craftconomy.bank.withdraw: true
    Craftconomy.banks.*:
        description: Give access only to higher level commands for bank
        children:
          Craftconomy.banks.give: true
          Craftconomy.banks.take: true
          Craftconomy.banks.set: true
    Craftconomy.bankuser:
        description: Give access to the player bank account commands
        children:
          Craftconomy.banks.holdings: true
          Craftconomy.bank.deposit: true
          Craftconomy.bank.withdraw: true
    Craftconomy.bankplus:
        description: Give access to the user plus only commands
        children:
          Craftconomy.banks.holdings: true
          Craftconomy.banks.holdings.others: true
          Craftconomy.bank.deposit: true
          Craftconomy.bank.withdraw: true
    Craftconomy.accounts.*:
        description: Gives access only to higher level commands
        children:
            Craftconomy.accounts.create: true
            Craftconomy.accounts.remove: true
            Craftconomy.accounts.give: true
            Craftconomy.accounts.take: true
            Craftconomy.accounts.set: true
            Craftconomy.accounts.purge: true
            Craftconomy.accounts.empty: true
    Craftconomy.plus:
        description: Gives access to user plus only commands
        children:
            Craftconomy.help: true
            Craftconomy.holdings: true
            Craftconomy.holdings.others: true
            Craftconomy.payment: true
    Craftconomy.user:
        description: Gives access to user only commands
        children:
            Craftconomy.help: true
            Craftconomy.holdings: true
            Craftconomy.payment: true
    Craftconomy.help:
        description: Allows you to request help information.
        default: op
        command: "/money help"
    Craftconomy.holdings:
        description: Check your balance.
        default: op
        command: "/money"
    Craftconomy.holdings.others:
        description: Check other players balance.
        default: op
        command: "/money <account-name>"
        examples:
          - "/money greatman"
    Craftconomy.payment:
        description: Send money to others.
        default: op
        command: "/money pay <account-name> <amount>"
        examples:
          - "/money pay greatman 30"
    Craftconomy.accounts.create:
        description: Create an account.
        default: op
        command: "/money create <account-name> [amount]"
        examples:
          - "/money create greatman"
          - "/money create greatman 30"
    Craftconomy.accounts.remove:
        description: Remove an existing account
        default: op
        command: "/money remove <account-name>"
        examples:
          - "/money remove greatman"
    Craftconomy.accounts.give:
        description: Give account a certain amount
        default: op
        command: "/money give <account-name> <amount>"
        examples:
          - "/money give greatman 30"
    Craftconomy.accounts.take:
        description: Take a certain amount from an account
        default: op
        command: "/money take <account-name> <amount>"
        examples:
          - "/money take greatman 30"
    Craftconomy.accounts.set:
        description: Set an account's balance to this amount
        default: op
        command: "/money set <account-name> <amount>"
        examples:
          - "/money set greatman 30"
    Craftconomy.accounts.purge:
        description: Purge all accounts with default creation value.
        default: op
        command: "/money purge"
    Craftconomy.accounts.empty:
        description: Empty / Drop entire database of accounts.
        default: op
        command: "/money empty"
    Craftconomy.banks.give:
        description: Give money in a bank account
        default: op
        command: "/bank give <account-name> <amount>"
    Craftconomy.banks.take:
        description: Take money in a bank account
        default: op
        command: "/bank take <account-name> <amount>"
    Craftconomy.banks.set:
        description: Set the bank account to a certain amount
        default: op
        command: "/bank set <account-name> <amount>"
    Craftconomy.banks.holdings:
        description: Check your bank holding
        default: op
        command: "/bank"
    Craftconomy.banks.holdings.others:
        description: Check someone else bank holdings
        default: op
        command: "/bank <account-name>"
    Craftconomy.bank.deposit:
        description: Deposit money in your bank account
        default: op
        command: "/bank deposit <amount>"
    Craftconomy.bank.withdraw:
        description: Withdraw money from your bank account
        default: op
        command: "/bank withdraw <amount>"