name: Craftconomy
main: me.greatman.Craftconomy.Craftconomy
version: 1.0.0 b-$BUILD_NUMBER
load: startup
commands:
    money:
      aliases: [craftconomy]
      description: Check / Distribute currency.
      
permissions:
    Craftconomy.*:
        default: op
        description: Gives access to all commands
        children:
            Craftconomy.help: true
            Craftconomy.holdings: true
            Craftconomy.holdings.others: true
            Craftconomy.payment: true
            Craftconomy.accounts.create: true
            Craftconomy.accounts.remove: true
            Craftconomy.accounts.give: true
            Craftconomy.accounts.take: true
            Craftconomy.accounts.set: true
            Craftconomy.accounts.status: true
            Craftconomy.accounts.status.set: true
            Craftconomy.accounts.purge: true
            Craftconomy.accounts.empty: true
    Craftconomy.accounts.*:
        description: Gives access only to higher level commands
        children:
            Craftconomy.accounts.create: true
            Craftconomy.accounts.remove: true
            Craftconomy.accounts.give: true
            Craftconomy.accounts.take: true
            Craftconomy.accounts.set: true
            Craftconomy.accounts.status: true
            Craftconomy.accounts.status.set: true
            Craftconomy.accounts.purge: true
            Craftconomy.accounts.empty: true
    Craftconomy.plus:
        description: Gives access to user plus only commands
        children:
            Craftconomy.help: true
            Craftconomy.holdings: true
            Craftconomy.holdings.others: true
            Craftconomy.payment: true
    Craftconomy.user:
        description: Gives access to user only commands
        children:
            Craftconomy.help: true
            Craftconomy.holdings: true
            Craftconomy.payment: true
    Craftconomy.help:
        description: Allows you to request help information.
        default: op
        command: "/money help"
    Craftconomy.holdings:
        description: Check your balance.
        default: op
        command: "/money"
    Craftconomy.holdings.others:
        description: Check other players balance.
        default: op
        command: "/money <account-name>"
        examples:
          - "/money Nijikokun"
    Craftconomy.payment:
        description: Send money to others.
        default: op
        command: "/money pay <account-name> <amount>"
        examples:
          - "/money pay Nijikokun 30"
    Craftconomy.accounts.create:
        description: Create an account.
        default: op
        command: "/money create <account-name> [amount]"
        examples:
          - "/money create Nijikokun"
          - "/money create Nijikokun 30"
    Craftconomy.accounts.remove:
        description: Remove an existing account
        default: op
        command: "/money remove <account-name>"
        examples:
          - "/money remove Nijikokun"
    Craftconomy.accounts.give:
        description: Give account a certain amount
        default: op
        command: "/money give <account-name> <amount>"
        examples:
          - "/money give Nijikokun 30"
    Craftconomy.accounts.take:
        description: Take a certain amount from an account
        default: op
        command: "/money take <account-name> <amount>"
        examples:
          - "/money take Nijikokun 30"
    Craftconomy.accounts.set:
        description: Set an account's balance to this amount
        default: op
        command: "/money set <account-name> <amount>"
        examples:
          - "/money set Nijikokun 30"
    Craftconomy.accounts.status:
        description: Check to see the status of an account (Visible, Hidden, Etc)
        default: op
        command: "/money status <account-name>"
        examples:
          - "/money status Nijikokun"
    Craftconomy.accounts.status.set:
        description: Set the status of an account (Visible (1), Hidden (0))
        default: op
        command: "/money status <account-name>"
        examples:
          - "/money status Nijikokun"
    Craftconomy.accounts.purge:
        description: Purge all accounts with default creation value.
        default: op
        command: "/money purge"
    Craftconomy.accounts.empty:
        description: Empty / Drop entire database of accounts.
        default: op
        command: "/money empty"